/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface KwWelcome {}
}

declare global {


  interface HTMLKwWelcomeElement extends Components.KwWelcome, HTMLStencilElement {}
  var HTMLKwWelcomeElement: {
    prototype: HTMLKwWelcomeElement;
    new (): HTMLKwWelcomeElement;
  };
  interface HTMLElementTagNameMap {
    'kw-welcome': HTMLKwWelcomeElement;
  }
}

declare namespace LocalJSX {
  interface KwWelcome {}

  interface IntrinsicElements {
    'kw-welcome': KwWelcome;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'kw-welcome': LocalJSX.KwWelcome & JSXBase.HTMLAttributes<HTMLKwWelcomeElement>;
    }
  }
}


